### ISSUE TITLE
1

### ISSUE THREAD

**Issue by ghost** [smallprogram/OpenWrtAction#1]

**Comment by smallprogram** [comment]
你这个是啥平台？

**Comment by lrios-jaxon** [comment]
> 你这个是什么平台？
P3TERX大佬的云编译

**Comment by smallprogram** [comment]
> > 你这个是什么平台？
> > P3TERX大佬的云编译

我的意思是你编译的是什么平台的固件，我看你这个Cortex-A5处理器，迅雷赚钱宝？

**Comment by lrios-jaxon** [comment]
> 

玩客云

**Comment by smallprogram** [comment]
> > 
> 
> 玩客云

不要意思，这个我真帮不上你，建议移步lean源码库提交ISSUE

**Comment by lrios-jaxon** [comment]
解决了哥们 我把架构换成了meson的就好了

**Comment by smallprogram** [comment]
> 解决了哥们 我把架构换成了meson的就好了

👍👍👍
