### ISSUE TITLE
建议修改x64配置

### ISSUE THREAD

**Issue by Jason6111** [smallprogram/OpenWrtAction#12]
L大把默认内核改为5.10了 最好改下x64配置 来适配5.10

**Comment by smallprogram** [comment]
> L大把默认内核改为5.10了 最好改下x64配置 来适配5.10

我再加个5.10的x64如何？

**Comment by Jason6111** [comment]
> 

哈哈哈 也可以 那你现在这个x64加个值吧 

# CONFIG_TESTING_KERNEL is not set
改为
CONFIG_TESTING_KERNEL=y  就是5.4了

**Comment by smallprogram** [comment]
等我晚上搞一下

**Comment by Jason6111** [comment]
你现在的改完了 你弄5.10的就行了

**Comment by smallprogram** [comment]
> 你现在的改完了 你弄5.10的就行了

不行，5.10有些插件时不兼容的，比如pptp啥的。我得回去仔细看看。

**Comment by Jason6111** [comment]
> > 你现在的改完了 你弄5.10的就行了
> 
> 不行，5.10有些插件时不兼容的，比如pptp啥的。我得回去仔细看看。

不是 我添加这个值就是让他保持在5.4的

**Comment by smallprogram** [comment]
嗷嗷嗷，了解了。

**Comment by smallprogram** [comment]
这个先这么着把，我试试5.10编出了怎么样，要是好，就直接5.10得了。省的费劲了
