### ISSUE TITLE
H68K添加SATA支持

### ISSUE THREAD

**Issue by jiawen94** [smallprogram/OpenWrtAction#15]
2024.8.12编译的LEDE固件（内核6.1.100），发现无法识别SATA硬盘。在询问] (https://github.com/coolsnowwolf/lede/issues/12416) 后得知 

> https://github.com/coolsnowwolf/lede/commit/54ad1c5009b07dca48eeaf7650345b41e1abcf66 6.1 要选上 `kmod-ata-ahci-dwc `

希望h68k固件的编译选项添加  `kmod-ata-ahci-dwc  ` (https://github.com/smallprogram/OpenWrtAction/blob/main/config/leanlede_config/H68K.config#L3023)

理论上所有rk3568在6.1内核下都存在这个问题，不过印象中只有hinlink的几款软路由才硬件上支持sata

**Comment by smallprogram** [comment]
修改了config，建议你使用wsl2op_lean.sh编译测试一下，或者等待明天中午的在线编译结果测试一下
@jiawen94

**Comment by jiawen94** [comment]
好的。这两天出差，我周末回去再验证一下sata功能，用在线编译的包

**Comment by jiawen94** [comment]
另外我想请教您一件事，openwrt/lede的固件升级，我们一般是通过web ui的`cgi-bin/luci/admin/system/flashops`上传sysupgrade固件升级吗？是否会产生脏数据之类的东西，有必要重写TF卡更新吗？

**Comment by smallprogram** [comment]
> 另外我想请教您一件事，openwrt/lede的固件升级，我们一般是通过web ui的`cgi-bin/luci/admin/system/flashops`上传sysupgrade固件升级吗？是否会产生脏数据之类的东西，有必要重写TF卡更新吗？

不会，没必要刷TF

**Comment by jiawen94** [comment]
谢谢，SATA可以识别了
![image](https://github.com/user-attachments/assets/e87f627f-d647-4621-aedc-fd6fcb908ead)
