### ISSUE TITLE
release 样式和企业微信应用通知

### ISSUE THREAD

**Issue by c939984606** [smallprogram/OpenWrtAction#16]
样式：
        echo "<details> <summary> Lean Openwrt Commit Top $COMMIT_LOG_NUM </summary>" >> release.txt
        echo "<br>" >> release.txt
        echo "" >> release.txt
        echo -e "> $(git -C openwrt log -n $COMMIT_LOG_NUM)" >> release.txt
        echo "" >> release.txt
        echo "</details>" >> release.txt

       企业微信应用通知：
        starttime=$(echo `date +'%Y-%m-%d %H:%M:%S'`)
        url="https://qyapi.weixin.qq.com/cgi-bin"
        token=`curl -s "$url/gettoken?corpid=${{ secrets.ID }}&corpsecret=${{ secrets.SECRET }}"|jq -r .access_token`
        curl --location --request POST 'https://qyapi.weixin.qq.com/cgi-bin/message/send?access_token='"${token}"'' \
        --header 'Content-Type: application/json' \
        --data-raw '{
          "touser" : "@all",
          "msgtype" : "textcard",
          "agentid" : ${{ secrets.AGENTID }},
          "textcard" : {
            "title" : "➤➤ 编译开始: ",
            "description" : "<div class=\"highlight\">🎉 固件名称：OpenWrt-'"${RELEASE_TAG}"'\n🎉 开始时间：'"${starttime}"'\n🎉 编译状态：进行中。。。 😋💐</div>",
            "url" : "https://github.com/替换你自己的网址/actions",
            "btntxt":"点击打开"
          },
        "enable_id_trans": 0,
        "enable_duplicate_check": 0,
        "duplicate_check_interval": 1800
        }'

![1](https://user-images.githubusercontent.com/34211368/158096357-050a604e-0392-4719-9145-21240a4f7187.png)

![2](https://user-images.githubusercontent.com/34211368/158096278-35221bb2-3d8c-4b0d-a273-f5d84d18e1f4.jpg)

**Comment by smallprogram** [comment]
welcome pr
