### ISSUE TITLE
请问一下大佬，config文件在每次源码更新后都会有一定的变化，如何自动更新？

### ISSUE THREAD

**Issue by weigeloveu** [smallprogram/OpenWrtAction#18]
我们平时config无非就是几个常用的固定插件跟功能，可否在lede源码更新后自动生成config文件，然后把我们想要的功能跟插件以补丁的形式打进去？我都是用的本办法在本地勾选好，生成config然后上传到git，感觉姿势不是很优雅，还请大佬指点一下

**Comment by smallprogram** [comment]
你指的云编译还是本地编译？

**Comment by weigeloveu** [comment]
> 你指的云编译还是本地编译？

云编译脚本，经常config就不能用了，然后我就本地重新拉源码配置一个config传上去，有没有简单的方法，不用每次都重新上传。我的想法是只把我们需要勾选的地方放上去，然后config文件让脚本自己生成

**Comment by smallprogram** [comment]
无论是本地还是云，编译流程其实是一样的，无非就这几步：
1. 更新op源码
2. make dirclean(云编译用不到，本地编译可选适用于大版本更新)
3. 更新feeds、安装feeds
4. 注入.config
5. make defconfig (这步解决源码更新后config不匹配的问题，无需重新make menuconfig)
6. make download 预下载编译所需要的依赖
7. 编译

你的问题应该使用第五步就能解决。就像这样：

![image](https://user-images.githubusercontent.com/6050360/168195153-636d416d-fe15-4da9-846c-ce24467f00a6.png)
