### ISSUE TITLE
大佬你的硬酷R1的硬盘是什么型号的？我的安装ESXI认不到盘

### ISSUE THREAD

**Issue by ion-lgb** [smallprogram/OpenWrtAction#2]
大佬你的硬酷R1的硬盘是什么型号的？我的安装ESXI认不到盘

**Comment by smallprogram** [comment]
就原装的。n6005那款16G内存那个

**Comment by smallprogram** [comment]
![image](https://user-images.githubusercontent.com/6050360/233581884-2fc1c386-148c-4748-b098-d9878eb54c80.png)
@ion-lgb
