### ISSUE TITLE
r2s 默认地址无法链接到openwrt

### ISSUE THREAD

**Issue by aboluo12138** [smallprogram/OpenWrtAction#3]
## 描述bug
默认地址:10.10.0.253无法链接到openwrt后台
![1](https://github.com/smallprogram/OpenWrtAction/assets/38574949/3ad5fba0-b136-40c1-823c-267e6fb5ca7b)
![2](https://github.com/smallprogram/OpenWrtAction/assets/38574949/941dcd15-a379-4f96-93f4-5dd3ae00160b)

**Comment by smallprogram** [comment]
最近我在大改编译脚本，可能固件都有点问题。

**Comment by aboluo12138** [comment]
原来如此，我还以为是我的问题

**Comment by smallprogram** [comment]
你可以尝试在本地，用我那个wsl2.op.sh编译R2S，那个没有问题，具体方法看readme。
我也可以简单的说一下
1. 进入你的linux系统，安装lede编译前的那些包
2. 执行`git clone https://github.com/smallprogram/OpenWrtAction`
3. `cd OpenWrtAction`
4. `bash wsl2op.sh`
5. 按照菜单提示一步一步选择执行即可
