### ISSUE TITLE
求新增SmartDNS主要做分流用的

### ISSUE THREAD

**Issue by ZacharyBacon** [smallprogram/OpenWrtAction#4]
SmartDNS主要是区分国内外ip不同dns，感觉很有必要的。

**Comment by smallprogram** [comment]
> SmartDNS主要是区分国内外ip不同dns，感觉很有必要的。

SmartDNS已经包含在固件中了
至于配置，你需要自己配

**Comment by ZacharyBacon** [comment]
好的那，感谢大佬。。。
